language: php

dist:     xenial

php:
    -     7.0
    -     7.1
    -     7.2

compiler:
    -     gcc

sudo:     required

before_script:
    -     git submodule update --init

script:
    -     sudo apt -y install libuv1-dev libssl-dev openssl
    -     phpize
    -     ./configure --with-openssl --enable-debug-respondphp
    -     make clean all
    -     NO_INTERACTION=1 make test
