dist:     xenial

addons:
    apt:
        sources:
            -     ppa:ondrej/apache2
        packages:
            -     libuv1-dev
            -     libssl-dev
            -     openssl

language: php

php:
    -     7.0
    -     7.1
    -     7.2

compiler:
    -     gcc

sudo:     required

before_script:
    -     git submodule update --init

script:
    -     phpize
    -     ./configure --with-openssl --enable-debug-respondphp
    -     make clean all
    -     NO_INTERACTION=1 make test
