dist:     xenial

addons:
    apt:
        packages:
            -     libuv1-dev
            -     libssl-dev
            -     openssl

language: php

php:
    -     7.1
    -     7.2

compiler:
    -     gcc

sudo:     required

before_script:
    -     git submodule update --init

script:
    -     phpize
    -     ./configure --with-openssl --enable-debug-respondphp
    -     make clean all
    -     NO_INTERACTION=1 php run-tests.php --show-diff -d extension=modules/respondphp.so
    -     php thirdparty/composer.phar -dphpsrc install
    -     php phpsrc/vendor/bin/phpunit --bootstrap phpsrc/tests/bootstrap.php phpsrc/tests
