dist:     xenial

addons:
    apt:
        packages:
            -     libuv1-dev
            -     libssl-dev
            -     openssl

language: php

php:
    -     7.1
    -     7.2

compiler:
    -     gcc

sudo:     required

before_script:
    -     sudo add-apt-repository ppa:ondrej/apache2 -y
    -     sudo apt update
    -     sudo apt upgrade libuv1-dev libssl-dev openssl -y
    -     git submodule update --init

script:
    -     phpize
    -     ./configure --with-openssl --enable-debug-respondphp
    -     make clean all
    -     NO_INTERACTION=1 make test
