#ifndef RESPONDPHP_SSL_DETECT_H
#define RESPONDPHP_SSL_DETECT_H

#if OPENSSL_VERSION_NUMBER < 0x10100000L
#define SECURE_SERVER_METHOD TLSv1_method
#else
#define SECURE_SERVER_METHOD TLS_server_method
#endif

#ifndef OPENSSL_NO_TLSEXT
#define HAVE_TLS_SNI 1
#if OPENSSL_VERSION_NUMBER >= 0x10002000L
#define HAVE_TLS_ALPN 1
#endif
#endif

#endif //RESPONDPHP_SSL_DETECT_H
