#ifndef _RESPOND_VERSION_H
#define _RESPOND_VERSION_H

#define _VERSION_STR_HELPER(x) #x
#define _VERSION_STR(x) _VERSION_STR_HELPER(x)

#define RESPOND_VERSION_MAJOR 0
#define RESPOND_VERSION_MINOR 0
#define RESPOND_VERSION_PATCH 1
#define RESPOND_VERSION_IS_RELEASE 0
#define RESPOND_VERSION_SUFFIX "dev"

#define RESPOND_VERSION_HEX  ((RESPOND_VERSION_MAJOR << 16) | \
                         (RESPOND_VERSION_MINOR <<  8) | \
                         (RESPOND_VERSION_PATCH))
#define RESPOND_VERSION_STRING _VERSION_STR(RESPOND_VERSION_MAJOR) "."  _VERSION_STR(RESPOND_VERSION_MINOR) "." _VERSION_STR(RESPOND_VERSION_PATCH) RESPOND_VERSION_SUFFIX
#endif
